# ✅ This is the root of the whole GitOps tree
# ✅ It tells Flux to apply everything from "apps" and "monitoring"

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps        # ✅ This is a FOLDER, not a file!
  - monitoring  # ✅ Also a FOLDER with its own kustomization.yaml
