# 🚀 This is the master plan that Flux uses
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps        # 📦 Loads the apps/kustomization.yaml (which loads all apps)
  - monitoring  # 📊 Loads monitoring tools (Grafana + Prometheus)
